from tkinter import *
def plus():
    xx=eval(x.get())
    yy=eval(y.get())
    zz=str(xx+yy)
    z.set('product:'+zz)
def vernus():
    xx=eval(x.get())
    yy=eval(y.get())
    zz=str(xx-yy)
    z.set('product:'+zz)
def time():
    xx=eval(x.get())
    yy=eval(y.get())
    zz=str(xx*yy)
    z.set('product:'+zz)

W=Tk()
W.title('Calculate')
F=Label(W,text='First\nnumber:')
F.grid(row=0,column=0,padx=5,pady=5,sticky=S)
add=Button(W,text='+',command=plus)
add.grid(row=0,column=1,padx=5,pady=5)
subtract=Button(W,text='-',command=vernus)
subtract.grid(row=1,column=1,padx=5,pady=5)
multify=Button(W,text='X',command=time)
multify.grid(row=2,column=1,padx=5,pady=5)
S=Label(W,text='Secend\nnumber:')
S.grid(row=0,column=2,padx=5,pady=5)
x=StringVar()
x.set('')
y=StringVar()
y.set('')
z=StringVar()
z.set('')
Fn=Entry(W,textvariable=x,width=3)
Fn.grid(row=1,column=0,padx=5,pady=5,sticky=N)
Sn=Entry(W,textvariable=y,width=3)
Sn.grid(row=1,column=2,padx=5,pady=5,sticky=N)
product=Entry(W,textvariable=z,state='readonly',width=5)
product.grid(padx=10,pady=10,sticky=EW)
W.mainloop()